name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Frontend image
        run: docker pull mawlle/maxgram-frontend

      - name: Pull Backend image
        run: docker pull mawlle/maxgram

      - name: Restart Docker Compose
        run: docker compose down

      - name: Deploy with Docker Compose
        run: docker compose up -d
